DROP TABLE IF EXISTS posts;

CREATE TABLE tabelas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nome TEXT NOT NULL,
    content TEXT NOT NULL
);